export const getUserHelper = (): string => '/users/profile'
export const postUserAuth = (): string => '/auth'
export const postAuthKey = (): string => '/auth/confirmation/'
export const getAllOrders = (): string => '/orders/get-all/'
export const getMinOrders = (): string => '/orders/get-min-orders/'
export const createOrder = (): string => '/orders/create'
export const deleteOrder = (): string => '/orders'
export const orderChangeStatus = (): string => '/orders/status'
export const orderEdit = (): string => '/orders/order-edit'
export const checkPay = (): string => '/orders/payment-verification'
export const getAllUsers = (): string => '/users/all-user'
export const updateUser = (): string => '/users/update'
export const updateUserName = (): string => '/users/add-name'
export const createCard = (): string => '/cards/add'
export const deleteCard = (): string => '/cards/delete/'
export const deleteCardImage = (): string => '/cards/delete-image'
export const pushCardImage = (): string => '/cards/push-image'
export const updateCard = (): string => '/cards/update'
export const getCardByTag = (): string => '/cards/get-cards-by-tag'
export const getCardById = (): string => '/cards/get-by-id'
export const deleteInvitationInfo = (): string => '/orders/delete-card-info'
export const changeOrderPrice = (): string => '/orders/change-price'
export const changeOrderPhoneNumber = (): string => '/orders/change-phone-number'

export const electronicGetAll = (): string => '/electronic'
export const electronicCreate = (): string => '/electronic/create'
export const electronicDelete = (): string => '/electronic'

export type TAuth = {
	response: 'activation key sent for new user'
}
